name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*" # Triggers on tags that start with 'v', like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/newschatbot-frontend:latest
            ghcr.io/${{ github.repository_owner }}/newschatbot-frontend:${{ steps.tag.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
